// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATS7YuCvJcsbgM_8r0D64Sn-LRis1jxR4',
    appId: '1:1001959925317:web:d80a08db670b7255f7652c',
    messagingSenderId: '1001959925317',
    projectId: 'push-notification-67c3c',
    authDomain: 'push-notification-67c3c.firebaseapp.com',
    storageBucket: 'push-notification-67c3c.appspot.com',
    measurementId: 'G-1PDEF469D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9uBFXeOkPZBMcEwkF1dDgWSWepKRo9fk',
    appId: '1:1001959925317:android:22ee33369c4b82d2f7652c',
    messagingSenderId: '1001959925317',
    projectId: 'push-notification-67c3c',
    storageBucket: 'push-notification-67c3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfPSWh-Mfgal-Wk_GafczwVhaxt_rJh04',
    appId: '1:1001959925317:ios:7579cb8e23563584f7652c',
    messagingSenderId: '1001959925317',
    projectId: 'push-notification-67c3c',
    storageBucket: 'push-notification-67c3c.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfPSWh-Mfgal-Wk_GafczwVhaxt_rJh04',
    appId: '1:1001959925317:ios:7579cb8e23563584f7652c',
    messagingSenderId: '1001959925317',
    projectId: 'push-notification-67c3c',
    storageBucket: 'push-notification-67c3c.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATS7YuCvJcsbgM_8r0D64Sn-LRis1jxR4',
    appId: '1:1001959925317:web:5d89ac6c1f3c692cf7652c',
    messagingSenderId: '1001959925317',
    projectId: 'push-notification-67c3c',
    authDomain: 'push-notification-67c3c.firebaseapp.com',
    storageBucket: 'push-notification-67c3c.appspot.com',
    measurementId: 'G-FRDB1XNZFP',
  );

}